module.exports = {
  'mm_buyPercent': 0.67,
  'mm_minInterval': 60000,
  'mm_maxInterval': 360000,
  'mm_isActive': false,
  'mm_minAmount': 0.1,
  'mm_maxAmount': 202,
  'mm_Policy': 'optimal',
  'mm_isOrderBookActive': true,
  'mm_orderBookHeight': 10,
  'mm_orderBookOrdersCount': 10,
  'mm_isLiquidityActive': false,
  'mm_liquiditySellAmount': 100,
  'mm_liquidityBuyQuoteAmount': 50,
  'mm_liquiditySpreadPercent': 2,
  'mm_liquidityTrend': 'middle',
  'mm_isPriceWatcherActive': false,
  'mm_priceWatcherLowPriceInSourceCoin': 0,
  'mm_priceWatcherMidPriceInSourceCoin': 0,
  'mm_priceWatcherHighPriceInSourceCoin': 0,
  'mm_priceWatcherDeviationPercent': 0,
  'mm_priceWatcherSource': '#',
  'mm_priceWatcherSourcePolicy': 'smart',
  'mm_priceWatcherAction': 'fill',
};
