module.exports = {
   "mm_buyPercent": 0.67,
   "mm_minInterval": 3000,
   "mm_maxInterval": 350000,
   "mm_isActive": true,
   "mm_minAmount": 14,
   "mm_maxAmount": 1600,
   "mm_Policy": "optimal",
   "mm_isOrderBookActive": true,
   "mm_orderBookHeight": 25,
   "mm_orderBookOrdersCount": 20,
   "mm_isLiquidityActive": true,
   "mm_liquiditySellAmount": 2000,
   "mm_liquidityBuyQuoteAmount": 20,
   "mm_liquiditySpreadPercent": 1.5,
   "mm_liquidityTrend": "middle",
   "mm_isPriceWatcherActive": false,
   "mm_priceWatcherLowPriceInSourceCoin": 0,
   "mm_priceWatcherMidPriceInSourceCoin": 0,
   "mm_priceWatcherHighPriceInSourceCoin": 0,
   "mm_priceWatcherDeviationPercent": 0,
   "mm_priceWatcherSource": "#",
   "mm_priceWatcherSourcePolicy": "smart",
   "mm_priceWatcherAction": "fill"
}