module.exports = {
   "mm_buyPercent": 0.67,
   "mm_minInterval": 10000,
   "mm_maxInterval": 20000,
   "mm_isActive": true,
   "mm_minAmount": 14,
   "mm_maxAmount": 1600,
   "mm_Policy": "optimal",
   "mm_isOrderBookActive": false,
   "mm_orderBookHeight": 25,
   "mm_orderBookOrdersCount": 20,
   "mm_isLiquidityActive": true,
   "mm_liquiditySellAmount": 100,
   "mm_liquidityBuyQuoteAmount": 5,
   "mm_liquiditySpreadPercent": 2,
   "mm_liquidityTrend": "middle",
   "mm_isPriceWatcherActive": false,
   "mm_priceWatcherLowPrice": 0.98,
   "mm_priceWatcherMidPrice": 1,
   "mm_priceWatcherHighPrice": 1.02,
   "mm_priceWatcherDeviationPercent": 2,
   "mm_priceWatcherSource": "const",
   "mm_priceWatcherAction": "fill"
}