module.exports = {
   "mm_buyPercent": 0.67,
   "mm_minInterval": 60000,
   "mm_maxInterval": 360000,
   "mm_isActive": false,
   "mm_minAmount": 0.1,
   "mm_maxAmount": 202,
   "mm_Policy": "optimal",
   "mm_isOrderBookActive": true,
   "mm_orderBookHeight": 10,
   "mm_orderBookOrdersCount": 10,
   "mm_isLiquidityActive": false,
   "mm_liquiditySellAmount": 100,
   "mm_liquidityBuyAmount": 50,
   "mm_liquiditySpreadPercent": 2,
   "mm_liquidityTrend": "middle",
   "mm_isPriceWatcherActive": false,
   "mm_priceWatcherLowPrice": 0.98,
   "mm_priceWatcherMidPrice": 1,
   "mm_priceWatcherHighPrice": 1.02,
   "mm_priceWatcherDeviationPercent": 2,
   "mm_priceWatcherSource": "const",
   "mm_priceWatcherAction": "fill"
}