'use strict';

/**
 * Transfer funds object definition.
 * @typedef {Object} TransferEntries
 * @prop {"FAILED" | "PENDING" | "STATUS_UNKNOWN" | "SUCCESS"} status "SUCCESS" Transfer status.
 * @prop {string} transferId "01234567-89ab-cdef-0123-456789abcdef" Transfer UUID manually generated by us on request.
 * @typedef {Object} Transfer
 * @prop {string} retMsg "OK" Response status message.
 * @prop {TransferEntries} result
 * @prop {string} [bybitErrorInfo] E.g., '[131203] request parameter err: fromAccountType can't be toAccountType (No description)'
 */

module.exports = {};
