services:
  mm-app:
    image: ghcr.io/adamant-im/adamant-tradebot:latest
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      MM_DOCKER: "1"
    volumes:
      - ./config:/app/config
      - ./trade-config:/app/trade-config
      - ./logs:/app/logs
    restart: unless-stopped

  mongo:
    image: mongo:8
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
